export const CITATIONS = [
  // Data Sources
  {
    id: 'open-meteo',
    type: 'data',
    authors: 'Zippenfenig, P.',
    year: '2023',
    title: 'Open-Meteo.com Weather API',
    publisher: 'Zenodo',
    url: 'https://doi.org/10.5281/zenodo.7970649',
  },
  {
    id: 'beck-koppen',
    type: 'data',
    authors: 'Beck, H. E., Zimmermann, N. E., McVicar, T. R., Vergopolan, N., Berg, A., & Wood, E. F.',
    year: '2018',
    title: 'Present and future Köppen-Geiger climate classification maps at 1-km resolution',
    publisher: 'Scientific Data, 5, 180214',
    url: 'https://doi.org/10.1038/sdata.2018.214',
  },
  {
    id: 'openfreemap',
    type: 'data',
    authors: 'OpenFreeMap contributors',
    year: '2026',
    title: 'OpenFreeMap — free vector map tiles',
    publisher: 'OpenFreeMap',
    url: 'https://openfreemap.org',
  },
  {
    id: 'openstreetmap',
    type: 'data',
    authors: 'OpenStreetMap contributors',
    year: '2026',
    title: 'OpenStreetMap',
    publisher: 'OpenStreetMap Foundation',
    url: 'https://www.openstreetmap.org/copyright',
  },
  // Station Wikipedia Sources
  {
    id: 'fuji-wikipedia',
    type: 'data',
    authors: 'Wikipedia contributors',
    year: '2026',
    title: 'Fuji, Shizuoka',
    publisher: 'Wikipedia, The Free Encyclopedia',
    url: 'https://en.wikipedia.org/wiki/Fuji,_Shizuoka',
  },
  {
    id: 'matsue-wikipedia',
    type: 'data',
    authors: 'Wikipedia contributors',
    year: '2026',
    title: 'Matsue',
    publisher: 'Wikipedia, The Free Encyclopedia',
    url: 'https://en.wikipedia.org/wiki/Matsue',
  },
  {
    id: 'sangju-wikipedia',
    type: 'data',
    authors: 'Wikipedia contributors',
    year: '2026',
    title: 'Sangju',
    publisher: 'Wikipedia, The Free Encyclopedia',
    url: 'https://en.wikipedia.org/wiki/Sangju',
  },
  {
    id: 'sangju-gov',
    type: 'data',
    authors: 'Sangju City',
    year: '2026',
    title: 'Sangju City — Official Statistics',
    publisher: 'Sangju City Government',
    url: 'https://www.sangju.go.kr/eng/page/15013/10790.tc',
  },
  {
    id: 'rongcheng-wikipedia',
    type: 'data',
    authors: 'Wikipedia contributors',
    year: '2026',
    title: 'Rongcheng, Shandong',
    publisher: 'Wikipedia, The Free Encyclopedia',
    url: 'https://en.wikipedia.org/wiki/Rongcheng,_Shandong',
  },
  {
    id: 'yangxin-wikipedia',
    type: 'data',
    authors: 'Wikipedia contributors',
    year: '2026',
    title: 'Yangxin County, Hubei',
    publisher: 'Wikipedia, The Free Encyclopedia',
    url: 'https://en.wikipedia.org/wiki/Yangxin_County,_Hubei',
  },
  {
    id: 'loufan-wikipedia',
    type: 'data',
    authors: 'Wikipedia contributors',
    year: '2026',
    title: 'Loufan County',
    publisher: 'Wikipedia, The Free Encyclopedia',
    url: 'https://en.wikipedia.org/wiki/Loufan_County',
  },
  {
    id: 'shizuishan-wikipedia',
    type: 'data',
    authors: 'Wikipedia contributors',
    year: '2026',
    title: 'Shizuishan',
    publisher: 'Wikipedia, The Free Encyclopedia',
    url: 'https://en.wikipedia.org/wiki/Shizuishan',
  },
  {
    id: 'zhangye-wikipedia',
    type: 'data',
    authors: 'Wikipedia contributors',
    year: '2026',
    title: 'Zhangye',
    publisher: 'Wikipedia, The Free Encyclopedia',
    url: 'https://en.wikipedia.org/wiki/Zhangye',
  },
  {
    id: 'dunhuang-wikipedia',
    type: 'data',
    authors: 'Wikipedia contributors',
    year: '2026',
    title: 'Dunhuang',
    publisher: 'Wikipedia, The Free Encyclopedia',
    url: 'https://en.wikipedia.org/wiki/Dunhuang',
  },
  {
    id: 'lopnur-wikipedia',
    type: 'data',
    authors: 'Wikipedia contributors',
    year: '2026',
    title: 'Lop Nur',
    publisher: 'Wikipedia, The Free Encyclopedia',
    url: 'https://en.wikipedia.org/wiki/Lop_Nur',
  },
  {
    id: 'lopnur-baidu',
    type: 'data',
    authors: 'Baidu Baike',
    year: '2026',
    title: 'Lop Nor Town',
    publisher: 'Baidu Baike',
    url: 'https://baike.baidu.com/en/item/Lop%20Nor%20Town/933310',
  },
  {
    id: 'nasa-lopnur',
    type: 'data',
    authors: 'NASA Earth Observatory',
    year: '2011',
    title: 'Lop Nur, Xinjiang, China',
    publisher: 'NASA Earth Observatory',
    url: 'https://science.nasa.gov/earth/earth-observatory/lop-nur-xinjiang-china-51039/',
  },
  // Ocean Current Sources
  {
    id: 'currents-of-japan',
    type: 'data',
    authors: 'Blue Japan',
    year: '2026',
    title: 'Currents of Japan',
    publisher: 'Blue Japan',
    url: 'https://bluejapan.org/geography/currents-of-japan/',
  },
  {
    id: 'tsushima-current',
    type: 'data',
    authors: 'Britannica editors',
    year: '2026',
    title: 'Tsushima Current',
    publisher: 'Encyclopaedia Britannica',
    url: 'https://www.britannica.com/place/Tsushima-Current',
  },
  // Pressure System Sources
  {
    id: 'siberian-high',
    type: 'data',
    authors: 'Wikipedia contributors',
    year: '2026',
    title: 'Siberian High',
    publisher: 'Wikipedia, The Free Encyclopedia',
    url: 'https://en.wikipedia.org/wiki/Siberian_High',
  },
  {
    id: 'north-pacific-high',
    type: 'data',
    authors: 'Wikipedia contributors',
    year: '2026',
    title: 'North Pacific High',
    publisher: 'Wikipedia, The Free Encyclopedia',
    url: 'https://en.wikipedia.org/wiki/North_Pacific_High',
  },
  {
    id: 'aleutian-low',
    type: 'data',
    authors: 'Wikipedia contributors',
    year: '2026',
    title: 'Aleutian Low',
    publisher: 'Wikipedia, The Free Encyclopedia',
    url: 'https://en.wikipedia.org/wiki/Aleutian_Low',
  },
  // Tools & Libraries
  {
    id: 'react',
    type: 'tool',
    authors: 'Meta Platforms, Inc.',
    year: '2026',
    title: 'React — The library for web and native user interfaces',
    publisher: 'Meta Open Source',
    url: 'https://react.dev',
  },
  {
    id: 'vite',
    type: 'tool',
    authors: 'VoidZero Inc. and Vite contributors',
    year: '2026',
    title: 'Vite — Next Generation Frontend Tooling',
    publisher: 'Vite',
    url: 'https://vitejs.dev',
  },
  {
    id: 'react-router',
    type: 'tool',
    authors: 'Shopify, Inc.',
    year: '2026',
    title: 'React Router',
    publisher: 'Shopify, Inc.',
    url: 'https://reactrouter.com',
  },
  {
    id: 'maplibre-gl',
    type: 'tool',
    authors: 'MapLibre contributors',
    year: '2026',
    title: 'MapLibre GL JS — Open-source mapping library',
    publisher: 'MapLibre',
    url: 'https://maplibre.org/maplibre-gl-js/docs/',
  },
  {
    id: 'react-map-gl',
    type: 'tool',
    authors: 'OpenJS Foundation and vis.gl contributors',
    year: '2026',
    title: 'react-map-gl — React components for MapLibre GL JS',
    publisher: 'OpenJS Foundation',
    url: 'https://visgl.github.io/react-map-gl/',
  },
  {
    id: 'recharts',
    type: 'tool',
    authors: 'Recharts Group',
    year: '2026',
    title: 'Recharts — Redefined chart library built with React and D3',
    publisher: 'Recharts',
    url: 'https://recharts.org',
  },
  {
    id: 'turf',
    type: 'tool',
    authors: 'Turfjs contributors',
    year: '2026',
    title: 'Turf.js — Advanced geospatial analysis for browsers and Node.js',
    publisher: 'Turfjs',
    url: 'https://turfjs.org',
  },
  {
    id: 'claude-code',
    type: 'tool',
    authors: 'Anthropic, PBC',
    year: '2026',
    title: 'Claude Code — Agentic AI coding tool',
    publisher: 'Anthropic',
    url: 'https://claude.ai/code',
  },
  {
    id: 'glasmeyer-gist',
    type: 'tool',
    authors: 'Jonathan Glasmeyer',
    year: '2026',
    title: 'GitHub Gist — jonathanglasmeyer',
    publisher: 'GitHub Gist',
    url: 'https://gist.github.com/jonathanglasmeyer/3a9e508a977cee38dfadf0dbace92f53',
  },
]
