export const CITATIONS = [
  // Data Sources
  {
    id: 'open-meteo',
    type: 'data',
    authors: 'Zippenfenig, P.',
    year: '2023',
    title: 'Open-Meteo.com Weather API',
    publisher: 'Zenodo',
    url: 'https://doi.org/10.5281/zenodo.7970649',
  },
  {
    id: 'beck-koppen',
    type: 'data',
    authors: 'Beck, H. E., Zimmermann, N. E., McVicar, T. R., Vergopolan, N., Berg, A., & Wood, E. F.',
    year: '2018',
    title: 'Present and future Köppen-Geiger climate classification maps at 1-km resolution',
    publisher: 'Scientific Data, 5, 180214',
    url: 'https://doi.org/10.1038/sdata.2018.214',
  },
  {
    id: 'openfreemap',
    type: 'data',
    authors: 'OpenFreeMap contributors',
    year: '2024',
    title: 'OpenFreeMap — free vector map tiles',
    publisher: 'OpenFreeMap',
    url: 'https://openfreemap.org',
  },
  {
    id: 'openstreetmap',
    type: 'data',
    authors: 'OpenStreetMap contributors',
    year: '2024',
    title: 'OpenStreetMap',
    publisher: 'OpenStreetMap Foundation',
    url: 'https://www.openstreetmap.org/copyright',
  },
  // Tools & Libraries
  {
    id: 'react',
    type: 'tool',
    authors: 'Meta Platforms, Inc.',
    year: '2024',
    title: 'React — The library for web and native user interfaces',
    publisher: 'Meta Open Source',
    url: 'https://react.dev',
  },
  {
    id: 'vite',
    type: 'tool',
    authors: 'Evan You and Vite contributors',
    year: '2024',
    title: 'Vite — Next Generation Frontend Tooling',
    publisher: 'Vite',
    url: 'https://vitejs.dev',
  },
  {
    id: 'react-router',
    type: 'tool',
    authors: 'Remix Software',
    year: '2024',
    title: 'React Router',
    publisher: 'Remix Software',
    url: 'https://reactrouter.com',
  },
  {
    id: 'maplibre-gl',
    type: 'tool',
    authors: 'MapLibre contributors',
    year: '2024',
    title: 'MapLibre GL JS — Open-source mapping library',
    publisher: 'MapLibre',
    url: 'https://maplibre.org/maplibre-gl-js/docs/',
  },
  {
    id: 'react-map-gl',
    type: 'tool',
    authors: 'Vis.gl contributors',
    year: '2024',
    title: 'react-map-gl — React components for MapLibre GL JS',
    publisher: 'Vis.gl',
    url: 'https://visgl.github.io/react-map-gl/',
  },
  {
    id: 'recharts',
    type: 'tool',
    authors: 'Recharts Group',
    year: '2024',
    title: 'Recharts — Redefined chart library built with React and D3',
    publisher: 'Recharts',
    url: 'https://recharts.org',
  },
  {
    id: 'turf',
    type: 'tool',
    authors: 'Turfjs contributors',
    year: '2024',
    title: 'Turf.js — Advanced geospatial analysis for browsers and Node.js',
    publisher: 'Turfjs',
    url: 'https://turfjs.org',
  },
]
